# Generated by Django 4.0.5 on 2022-06-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='project_cover/default.jpg', null=True, upload_to=''),
        ),
    ]
